spring:
  application:
    name: backend
  profiles:
    active: dev
  web:
    resources:
      static-locations: "file:./frontend/,classpath:/static/"
logging:
  file:
    name: logs/currency-analyzer.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  level:
    root: WARN
    cz.tul.stin.backend: WARN